### ISSUE TITLE
Return multiple files from the same output entry in a single local directory

### ISSUE THREAD

**Issue by paoloviviani** [alpha-unito/streamflow#464]
Currently when multiple files are requested as an output, i.e., with glob
```
 multiple_output_files:
    type: File
    outputBinding:
      glob:
        - "*.nc"
```
they are returned to the local StreamFlow machine as multiple folders with UUID names. This is not very practical, in particular when multiple runs of the same workflow coexist.
I would suggest to return all the files belonging to the same output entry (.e.g, "multiple_output_files") in the same local directory.
Also, adding a top level directory for each WF execution would improve the usability, but that would be an additional step.
