### ISSUE TITLE
Design question about using DAG for Kubernetes Operator

### ISSUE THREAD

**Issue by vsoch** [alpha-unito/streamflow#88]
Hi again! We have Kubernetes Operator that brings up an entire Flux Framework "MiniCluster" - https://flux-framework.org/flux-operator/ and I'm just starting to develop an ability to save state between MiniClusters ([basic example](https://flux-framework.org/flux-operator/tutorials/state.html)) so we could do something that run a subset of jobs for a workflow, save state, and then bring up a different resource.

I'm in the process of thinking about how to integrate workflows into this. Notably, Flux is not a workflow tool, it simply runs workflows. So what I have in mind (and what I want to discuss) is to be able to generate a DAG (can I do that with streamflow?) and then break jobs down into the smallest number of unique MiniClusters that are needed. As an example, let's say I have two processing jobs that look like this:

```console
job1 -> preprocess (cpu) --> postprocess (cpu) --> analysis (gpu) --> visualization (cpu)
job2 -> preprocess (cpu) --> postprocess (cpu) --> analysis (gpu) --> visualization (cpu)
```
We can assume that the need of a "gpu" vs "cpu" warrants a different MiniCluster. On a job submission system  you would ask for different node types. For a Kubernetes operator like this one you'd need to ask for a different MiniCluster. Given this is broken into a (flattened) DAG and job1 and job2 don't depend on one another, this would break down into the following:

```console
job1 preprocess (cpu)     job2 preprocess (cpu)
job1 postprocess (cpu)    job2 postprocess (cpu)
job1 analysis (gpu)       job2 analysis (gpu)
job1 visualization (cpu)  job2 visualization (cpu) 
```

And then we can see (theoretically) that we could run each of the pre and post processing steps for jobs 1 and 2 on the same MiniCluster, bring up a GPU MiniCluster for the analysis, and run the final visualization on another CPU cluster:

```console
---- Bring up CPU MiniCluster ----
job1 preprocess (cpu)     job2 preprocess (cpu)
job1 postprocess (cpu)    job2 postprocess (cpu)

---- Bring up GPU MiniCluster ----
job1 analysis (gpu)       job2 analysis (gpu)

---- Bring up CPU MiniCluster ----
job1 visualization (cpu)  job2 visualization (cpu) 
```

We have an entire Flux Operator SDK in Python that can easily handle creating / bringing down / monitoring the clusters [reference](https://github.com/flux-framework/flux-operator/blob/main/sdk/python/v1alpha1/examples/interactive-submit.py) and what I'm looking for explicitly is an ability to define a workflow file, and then generate a DAG that can be broken into pieces (with commands to run for each) based on the resources needed for each (likely in this case instance types if relevant and container bases). Is this something that would be possible using streamflow or a component of it?

**Comment by GlassOfWhiskey** [comment]
Not sure if I understood all the details here. However, I'll try to answer all the questions.
You can definitely run DAGs with StreamFlow. It relies on the [Common Workflow Language](https://commonwl.org) (CWL) to design workflows. Also, with the recently proposed [Loop extension](https://github.com/common-workflow-language/common-workflow-language/issues/495), the A of the DAG is no more a strict requirement: you can have iterative constructs in the workflows you define. This turns out to be very useful for HPC pipelines (simulations, optimizations, DNN training, ...).

So the D(A)G is 50% of the StreamFlow user interface. The other half is the definition of execution environments, called `deployments`. They can be single Docker/Singularity images, Docker Compose files, and other things, including Helm Charts (at the moment there is not a connector for pure Kubernetes files, but one is definitely in plans). Then the user can map each step of the workflow to a specific execution environment, e.g., step 1 to a SLURM instance, step 2 to the local machine, step 3 to a Docker container running on Kubernetes. All these things are defined in the `streamflow.yml` file.

StreamFlow distinguish three different things in an execution environment: the unit of deployment, the unit of scheduling, and the unit of execution. In the case of the Helm chart, the unit of deployment is the whole chart, the unit of scheduling is a given container name, and the unit of execution is a single replica of the container. Assume that a Helm chart produces this manifest:

```yaml
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app1
  labels:
    app: app1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: app1:latest
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app2
  labels:
    app: app2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: app2:latest
```
When the environment is deployed, all the containers are created. Users can choose to schedule their workflow step on either `app1` or `app2` containers through the `service` directive. Then, StreamFlow will allocate resources and schedule tasks according to the user declaration. Suppose that we want `step1` to be executed onto 2 replicas of `app1`. Then in the `streamflow.yml` file we will put:

```yaml
bindings:
  - step: /step1
    target:
      deployment: helm-env
      service: app1
      locations: 2
```

Given that, I think you could proceed in two ways for your use-case. If you want something generic, you can simply create a Helm chart with multiple `MiniCluster` definitions and map DAG steps onto generated containers. Or, if you want something more specific for your `MiniCluster` interface, you can create a more specific connector that extends the Helm connector and overrides some of the methods. In all cases, if you want multiple `MiniCluster` objects to be deployed at once, you should put them into a single `deployment`. Otherwise, you can put them into two different `deplyoment` definitions and their life-cycle will be managed independently.

I'll be happy to discuss with you, and also to support you if you need some additional features in the Helm connector (or a base Kubernetes connector). We also have a dedicated StreamFlow [matrix channel](https://matrix.to/#/#streamflow:matrix.org) where we can have more interactive discussions.
